/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CertificationRouteImport } from './routes/certification'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as RecommendRouteImport } from './routes/recommend'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AdminIngestRouteImport } from './routes/admin/ingest'
import { Route as AdminInsightsRouteImport } from './routes/admin/insights'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationRoute = CertificationRouteImport.update({
  id: '/certification',
  path: '/certification',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendRoute = RecommendRouteImport.update({
  id: '/recommend',
  path: '/recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIngestRoute = AdminIngestRouteImport.update({
  id: '/admin/ingest',
  path: '/admin/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInsightsRoute = AdminInsightsRouteImport.update({
  id: '/admin/insights',
  path: '/admin/insights',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/certification': typeof CertificationRoute
  '/chat': typeof ChatRoute
  '/labs': typeof LabsRoute
  '/recommend': typeof RecommendRoute
  '/search': typeof SearchRoute
  '/admin/ingest': typeof AdminIngestRoute
  '/admin/insights': typeof AdminInsightsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/certification': typeof CertificationRoute
  '/chat': typeof ChatRoute
  '/labs': typeof LabsRoute
  '/recommend': typeof RecommendRoute
  '/search': typeof SearchRoute
  '/admin/ingest': typeof AdminIngestRoute
  '/admin/insights': typeof AdminInsightsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/certification': typeof CertificationRoute
  '/chat': typeof ChatRoute
  '/labs': typeof LabsRoute
  '/recommend': typeof RecommendRoute
  '/search': typeof SearchRoute
  '/admin/ingest': typeof AdminIngestRoute
  '/admin/insights': typeof AdminInsightsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/certification'
    | '/chat'
    | '/labs'
    | '/recommend'
    | '/search'
    | '/admin/ingest'
    | '/admin/insights'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/certification'
    | '/chat'
    | '/labs'
    | '/recommend'
    | '/search'
    | '/admin/ingest'
    | '/admin/insights'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/certification'
    | '/chat'
    | '/labs'
    | '/recommend'
    | '/search'
    | '/admin/ingest'
    | '/admin/insights'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CertificationRoute: typeof CertificationRoute
  ChatRoute: typeof ChatRoute
  LabsRoute: typeof LabsRoute
  RecommendRoute: typeof RecommendRoute
  SearchRoute: typeof SearchRoute
  AdminIngestRoute: typeof AdminIngestRoute
  AdminInsightsRoute: typeof AdminInsightsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certification': {
      id: '/certification'
      path: '/certification'
      fullPath: '/certification'
      preLoaderRoute: typeof CertificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommend': {
      id: '/recommend'
      path: '/recommend'
      fullPath: '/recommend'
      preLoaderRoute: typeof RecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ingest': {
      id: '/admin/ingest'
      path: '/admin/ingest'
      fullPath: '/admin/ingest'
      preLoaderRoute: typeof AdminIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/insights': {
      id: '/admin/insights'
      path: '/admin/insights'
      fullPath: '/admin/insights'
      preLoaderRoute: typeof AdminInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CertificationRoute: CertificationRoute,
  ChatRoute: ChatRoute,
  LabsRoute: LabsRoute,
  RecommendRoute: RecommendRoute,
  SearchRoute: SearchRoute,
  AdminIngestRoute: AdminIngestRoute,
  AdminInsightsRoute: AdminInsightsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
